[project]
name = "multiplayer-online-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.4",
    "pyanimation>=0.7",
    "pygame>=2.6.1",
    "python-dotenv>=1.1.1",
    "websocket-client>=1.8.0",
]
